first start for dgit with z/OS 2.5 DSFS

diff --git a/bin/dgit-init b/bin/dgit-init
--- a/bin/dgit-init
+++ b/bin/dgit-init
@@ -52,20 +52,40 @@ if ! git --git-dir "${gitdir}" --work-tree "${worktree}" "init" ;then
   exit 8
 fi
 
-gitexcl="${worktree}/GITEXCL"
+dataset=false
+if [ "${worktree}##/dsfs/" != "${worktree}" ]; then
+  # We are dealing with a dataset-mapped directory
+  if [ "${worktree}##/dsfs/txt" = "${worktree}" ]; then
+    # Only support for 'txt' so fail
+    echo "dgit only supports a work-tree under /dsfs/txt" >&2
+    exit 8
+  else
+    dataset=true
+  fi
+fi
+
+gitexcl="${worktree}/gitexcl"
 if ! [ -f "${gitexcl}" ]; then
-  if ! /bin/echo "# List of datasets to exclude (initially all except GITATTR and GITEXCL)
+  if ${dataset}; then
+    echo "Need to pre-allocate dataset for gitexcl (temporary)" >&2
+    exit 4
+  fi
+  if ! /bin/echo "# List of datasets to exclude (initially all except gitattr and gitexcl)
 *
-!GITATTR
-!GITEXCL
+!gitattr
+!gitexcl
 " >"${gitexcl}" ; then
     echo "Unable to create initial exclusion list in ${gitexcl}. Need write access" >&2
     exit 4
   fi
 fi
 
-gitattr="${worktree}/GITATTR"
+gitattr="${worktree}/gitattr"
 if ! [ -f "${gitattr}" ]; then
+  if ${dataset}; then
+    echo "Need to pre-allocate dataset for gitexcl (temporary)" >&2
+    exit 4
+  fi
   if ! /bin/echo "# Attributes to use for files (EBCDIC CCSID 1047 by default)
 text zos-working-tree-encoding=IBM-1047" >"${gitattr}" ; then
     echo "Unable to create attributes file in ${gitattr}. Need write access" >&2
