working on clone

diff --git a/bin/dgit-add b/bin/dgit-add
--- a/bin/dgit-add
+++ b/bin/dgit-add
@@ -1,7 +1,9 @@
 #!/bin/env bash
 
 #
-# add dataset to git-managed list
+# add dataset to git-managed list. 
+# Add an explicit entry for the file to exclude if from the 'ignore' list
+# and then perform a standard 'git add'
 #
 Syntax()
 {
@@ -14,16 +16,48 @@ Where:
   exit 4
 }
 
-if [ $# -eq 0 ]; then
-  Syntax
+# read the options
+TEMP=`getopt -n dgit-add -o h --long help -- "$@"`
+eval set -- "$TEMP"
+
+gitdir=''
+worktree=''
+while true; do
+  case "$1" in
+    -h|--help)
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo "Internal Error!"
+      exit 8
+      ;;
+  esac
+done
+
+set -x
+if gitdir=$(git rev-parse --git-dir) ; then
+  exclude="${gitdir}/info/exclude"
+  if [ -f "${exclude}" ]; then 
+    echo "found exclude file"
+  else
+    echo "unable to find exclude file" >&2
+  fi
+else
+  echo "unable to find .git directory" >&2
 fi
 
-if [ "${1}x" = '-hx' ] || [ "${1}x" = '--helpx' ]; then
-  Syntax
+if worktree=$(git config --get core.worktree) ; then
+  if ! grep -e "^\!${2}\$" "${worktree}/GITEXCL" ; then
+    if ! echo "!${2}" >> "${worktree}/GITEXCL" ; then
+      echo "Unable to add !${2} to ${worktree}/GITEXCL" >&2
+      exit 8
+    fi
+  else
+    echo "File ${2} already in GITEXCL - GITEXCL not changed"
+  fi
 fi
-if [[ ${1:0:1} == "-" ]] ; then 
-  echo "Unknown option: $1" >&2
-  Syntax
-fi
-
-echo "git-add $@"
+git "$@"
diff --git a/bin/dgit-clone b/bin/dgit-clone
--- a/bin/dgit-clone
+++ b/bin/dgit-clone
@@ -6,24 +6,61 @@
 Syntax()
 {
   echo "Syntax:
-  [<option>]* <verb> [<parameters>]*
+  dgit-clone [<option>]* <url> <work-tree>
 Where:
-  <options may be one of:>
+  <option> may be one of:
   -h|--help: this help
+  -g|--separate-git-dir <directory> : git directory to clone into
   " >&2
   exit 4
 }
 
-if [ $# -eq 0 ]; then
+# read the options
+TEMP=`getopt -n dgit-init -o hg: --long help,separate-git-dir: -- "$@"`
+eval set -- "$TEMP"
+
+gitdir=''
+worktree=''
+while true; do
+  case "$1" in
+    -g|--separate-git-dir)
+      gitdir=$2
+      shift 2
+      ;;
+    -h|--help)
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo "Internal Error!"
+      exit 8
+      ;;
+  esac
+done
+
+set -x
+if [ $# -ne 3 ]; then
+  echo "URL and work-tree need to both be specified" >&2
   Syntax
 fi
 
-if [ "${1}x" = '-hx' ] || [ "${1}x" = '--helpx' ]; then
-  Syntax
+# git clone --separate-git-dir <git dir> <url> <work-tree>
+cloneurl="$2"
+worktree="$3"
+branch=$(git config --get init.defaultbranch)
+if [ -z "${branch}" ]; then
+  branch='main'
 fi
-if [[ ${1:0:1} == "-" ]] ; then 
-  echo "Unknown option: $1" >&2
-  Syntax
+if ! dgit-init --git-dir="${gitdir}" --work-tree="${worktree}" init ; then
+  echo "Unable to initialize git directory and work tree" >&2
+  exit 8
 fi
 
+if ! cd "${gitdir}" || ! git remote add "origin/${branch}" "${cloneurl}" ; then 
+  echo "Unable to establish remote to origin/${branch} ${cloneurl}" >&2
+  exit 8
+fi
 echo "git-clone $@"
